<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Appointments Backup - {{ ucfirst($filter) }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .info {
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-approved { color: #28a745; }
        .status-pending { color: #ffc107; }
        .status-denied { color: #dc3545; }
    </style>
</head>
<body>
    <div class="header">
        <h1>LegalConnect - Appointments Backup</h1>
        <p>Filter: {{ ucfirst($filter) }} | Generated: {{ $generated_at }} | Total Records: {{ $total_records }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Consulting Type</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($appointments as $appointment)
            <tr>
                <td>{{ $appointment->id }}</td>
                <td>{{ $appointment->fullname }}</td>
                <td>{{ $appointment->email }}</td>
                <td>{{ $appointment->phone }}</td>
                <td>{{ $appointment->address }}</td>
                <td>{{ $appointment->consulting }}</td>
                <td>{{ $appointment->selected_date }}</td>
                <td>{{ $appointment->selected_time }}</td>
                <td class="status-{{ $appointment->appointment_approval }}">
                    {{ ucfirst($appointment->appointment_approval) }}
                </td>
                <td>{{ \Carbon\Carbon::parse($appointment->created_at)->format('Y-m-d H:i') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by LegalConnect System | Confidential</p>
    </div>
</body>
</html>