<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Appointments Backup - {{ $filter }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header .info {
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f2f2f2;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #666;
            font-size: 10px;
        }
        .status-approved {
            color: #28a745;
        }
        .status-pending {
            color: #ffc107;
        }
        .status-denied {
            color: #dc3545;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LegalConnect - Appointments Backup</h1>
        <div class="info">
            Filter: {{ ucfirst($filter) }} | 
            Generated: {{ $generated_at }} | 
            Total Records: {{ $total_records }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Category</th>
                <th>Case Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Terms</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach($appointments as $index => $appointment)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $appointment['fullname'] }}</td>
                <td>{{ $appointment['email'] }}</td>
                <td>{{ $appointment['phone'] }}</td>
                <td>{{ $appointment['address'] }}</td>
                <td>{{ $appointment['category'] }}</td>
                <td>{{ $appointment['case_name'] }}</td>
                <td>{{ $appointment['selected_date'] }}</td>
                <td>{{ $appointment['selected_time'] }}</td>
                <td class="status-{{ strtolower($appointment['appointment_approval']) }}">
                    {{ ucfirst($appointment['appointment_approval']) }}
                </td>
                <td>{{ $appointment['term_status'] }}</td>
                <td>{{ date('Y-m-d', strtotime($appointment['created_at'])) }}</td>
                <td>{{ date('Y-m-d', strtotime($appointment['updated_at'])) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        This is an automated backup generated by LegalConnect System.
        Document generated on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>