<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Appointments Backup - <?php echo e($filter); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header .info {
            color: #666;
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f2f2f2;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            border: 1px solid #ddd;
            padding: 6px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #666;
            font-size: 10px;
        }
        .status-approved {
            color: #28a745;
        }
        .status-pending {
            color: #ffc107;
        }
        .status-denied {
            color: #dc3545;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LegalConnect - Appointment Logs Backup</h1>
        <div class="info">
            Filter: <?php echo e(ucfirst($filter)); ?> | 
            <?php if(isset($branch) && $branch): ?>
            Branch: <?php echo e($branch); ?> | 
            <?php endif; ?>
            Generated: <?php echo e($generated_at); ?> | 
            Total Records: <?php echo e($total_records); ?>

        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Category</th>
                <th>Case Name</th>
                <th>Branch Choosed</th> <!-- ADDED THIS COLUMN -->
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Terms</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($index + 1); ?></td>
                <td><?php echo e($appointment['fullname']); ?></td>
                <td><?php echo e($appointment['email']); ?></td>
                <td><?php echo e($appointment['phone']); ?></td>
                <td><?php echo e($appointment['address']); ?></td>
                <td><?php echo e($appointment['category']); ?></td>
                <td><?php echo e($appointment['case_name']); ?></td>
                <td><?php echo e($appointment['branch'] ?? 'N/A'); ?></td> <!-- ADDED THIS DATA CELL -->
                <td><?php echo e($appointment['selected_date']); ?></td>
                <td><?php echo e($appointment['selected_time']); ?></td>
                <td class="status-<?php echo e(strtolower($appointment['appointment_approval'])); ?>">
                    <?php echo e(ucfirst($appointment['appointment_approval'])); ?>

                </td>
                <td><?php echo e($appointment['term_status']); ?></td>
                <td><?php echo e(date('Y-m-d', strtotime($appointment['created_at']))); ?></td>
                <td><?php echo e(date('Y-m-d', strtotime($appointment['updated_at']))); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="footer">
        This is an automated backup generated by LegalConnect System.
        Document generated on <?php echo e(date('Y-m-d H:i:s')); ?>

    </div>
</body>
</html><?php /**PATH D:\xampp\htdocs\Legal connect final\LegalConnect\resources\views\pdf\appointments_table.blade.php ENDPATH**/ ?>