<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Appointments Backup - <?php echo e(ucfirst($filter)); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .info {
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-approved { color: #28a745; }
        .status-pending { color: #ffc107; }
        .status-denied { color: #dc3545; }
    </style>
</head>
<body>
    <div class="header">
        <h1>LegalConnect - Appointments Backup</h1>
        <p>Filter: <?php echo e(ucfirst($filter)); ?> | Generated: <?php echo e($generated_at); ?> | Total Records: <?php echo e($total_records); ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Consulting Type</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($appointment->id); ?></td>
                <td><?php echo e($appointment->fullname); ?></td>
                <td><?php echo e($appointment->email); ?></td>
                <td><?php echo e($appointment->phone); ?></td>
                <td><?php echo e($appointment->address); ?></td>
                <td><?php echo e($appointment->consulting); ?></td>
                <td><?php echo e($appointment->selected_date); ?></td>
                <td><?php echo e($appointment->selected_time); ?></td>
                <td class="status-<?php echo e($appointment->appointment_approval); ?>">
                    <?php echo e(ucfirst($appointment->appointment_approval)); ?>

                </td>
                <td><?php echo e(\Carbon\Carbon::parse($appointment->created_at)->format('Y-m-d H:i')); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by LegalConnect System | Confidential</p>
    </div>
</body>
</html><?php /**PATH D:\xampp\htdocs\LEGAL CONNECT\resources\views/pdf/appointments_table.blade.php ENDPATH**/ ?>